language: node_js
node_js:
  - "12"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  # - "0.12"
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - node_modules
